site_name: PhantasyStarDocs
site_url: https://phantasystardocs.github.io/
github_repo: https://github.com/phantasystardocs/phantasystardocs.github.io
site_description: Phantasy Star modding guides and tools
nav:
  - Home: index.md
  - Tools:
    - tools/index.md
    
    - Phantasy Star Universe/Portable series:
        - Common: tools/phantasy-star-universe-and-portable-series/common/general.md
    - Phantasy Star Zero:
        - Encryption and Archives: tools/phantasy-star-zero/encryption-and-archives/archives.md
        - Graphics Data: tools/phantasy-star-zero/graphics-data/graphics.md
  - Guides:
    - guides/index.md
    - Hedgehog Engine:
      - Common:
        - Lighting/GI:
          - Example Guide: guides/hedgehog-engine/common/lighting/example.md
      - Sonic Generations: 
        - File Formats:
          - XNCP: 
            - Basics: guides/hedgehog-engine/blueblur/files/xncp/basics.md
            - Animations: guides/hedgehog-engine/blueblur/files/xncp/anims.md
        - Level Editing:
          - Sonic GLvl: guides/hedgehog-engine/blueblur/levels/glvl.md
    - Other Engines:
      - Sonic The Hedgehog (2006):
        - Level Editing:
          - Sonic GLvl: guides/others/marathon/levels/glvl.md
  - Discoveries:
    - discoveries/index.md
    - Sonic Unleashed:
      - PlayStation 3:
        - Leftover Install Assets: discoveries/swa/ps3/install.md
    - Sonic Generations:
      - HUD:
        - Unused Time Eater Gauge: discoveries/blueblur/hud/blb_gauge.md
    - Sonic Lost World:
      - Levels:
        - Colors Leftovers: discoveries/sonic2013/levels/colors.md
        - Test Levels: discoveries/sonic2013/levels/test.md
        - Deleted Levels: discoveries/sonic2013/levels/deleted.md
        - Original Level Order: discoveries/sonic2013/levels/original-order.md
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - git-committers:
      exclude: 
        - index.md
        - tools/*
        - guides/index.md
        - discoveries/index.md
  - git-revision-date-localized:
      type: timeago
      exclude:
        - index.md
        - tools/*
        - guides/index.md
        - discoveries/index.md
theme:
  logo: assets/icon.svg
  favicon: assets/favicon.png
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to AMOLED mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: amoled
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
